import { useState } from "react";
import Head from "next/head";
import {
  Container,
  Button,
  Grid,
  Radio,
  Textarea,
  Text,
} from "@nextui-org/react";

export default function Home() {
  const [value, setValue] = useState("");
  const [encode, setEncode] = useState("");
  const [convert, setConvert] = useState("");

  const base64Encoder = ({ target }) => {
    let result;
    if (encode) {
      let buff = new Buffer.from(target.value);
      result = buff.toString("base64");
      console.log('"' + value + '" converted to Base64 is "' + result + '"');
    } else {
      const buff = new Buffer(target.value, "base64");
      result = buff.toString();
      console.log('"' + value + '" converted from Base64 is "' + result + '"');
    }
    setConvert(result);
  };

  return (
    <div>
      <Head>
        <title>toolbox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <h1>Base64 Encoder/Decoder</h1>
        <Grid.Container gap={3}>
          <Grid>
            <Radio.Group
              orientation="horizontal"
              //   label="Colors"
              defaultValue="1"
              onChange={(v) => setEncode(v == "1" ? true : false)}
            >
              <Radio value="1" color="primary">
                Encode
              </Radio>
              <Radio value="0" color="primary">
                Decode
              </Radio>
            </Radio.Group>
          </Grid>
        </Grid.Container>
        <Grid.Container gap={3}>
          <Grid xs={12}>
            <Textarea
              label={<Text h3>{encode ? "Encode" : "Decode"}</Text>}
              fullWidth
              onChange={(e) => setValue(e.target.value)}
              rows={6}
            />
          </Grid>
          <Grid xs={12}>
            <Button onClick={() => base64Encoder({ target: { value: value } })}>
              Convert
            </Button>
          </Grid>
          <Grid xs={12}>
            <Textarea
              label={<Text h5>Result</Text>}
              fullWidth
              value={convert}
              readOnly
              rows={6}
            />
          </Grid>
        </Grid.Container>
      </Container>
    </div>
  );
}
